### ISSUE TITLE
crate layout

### ISSUE THREAD

**Issue by goertzenator** [sdwolf/rebar3_rust#1]
1. Can I convince you to go with a crate and priv dir layout compatible with [`rust.mk`](https://github.com/goertzenator/rust.mk)? 

2. Can I further tempt you into making a generalized rebar3 plugin for Rust? (ie, not just for NIFs).  I just did this for `erlang.mk` but don't know a lot about rebar3.  I offer my guidance and the test app from `rust.mk`.

**Comment by sdwolf** [comment]
Yes 1. sounds like a great idea but I am not sure about what 2. should do. Should it just copy the compiled binaries to the priv dir?

**Comment by goertzenator** [comment]
Yes, that's all it does really.  There are some wrinkles around OSX support, and rust.mk does not handle all corner cases, but I wouldn't worry about the details at this point.  Just doing #1 would be a huge help.  I'd like to contribute to this project in the future.

**Comment by sdwolf** [comment]
I've commited 711c5b36ea7bf9ee29ad9ee7fab71d035f8b676f that handles .so files with the rust.mk dir structure. Working on making it more general.

**Comment by sdwolf** [comment]
With 8988b22ada54a7d441053ecd2fbca9df32babf23 now all relevant files from `target/release` are copied to the priv folder.

For renaming .dylib to .so, does cargo not support this as a config or flag? If not i can implement it as a config option for the plugin.

**Comment by goertzenator** [comment]
Thanks for changing the structure!

I've seen no cargo option for that.  I assumed that extension requirement was an oddball, non-standard requirement from Erlang, but I don't have OSX so I don't know the conventions.  On Windows, Erlang is perfectly happy with .dll extensions for NIFs.

IMO, the rename should be default behavior.  The same high level build command should work on Windows/Linux/OSX without platform specific flags.  A flag to disable that behavior is fine though, although maybe wait and see if there is a use case for disabling.

Before you dive too far into this plugin, consider this design approach: https://github.com/goertzenator/rust.mk/issues/3 .  This would unify our efforts and reduce duplication.

Backing up a bit, I don't want to presume that you are interested in doing all this work.  You wanted to add a link to erlang_nif-sys, and here I am shoveling requests, ideas, and work at you!  This is something I would chip away at on my own or ask for help in TWIR, but if you really want to be involved with this, then that's great too.

**Comment by sdwolf** [comment]
2b9aecfc0cd989c3a76289740ee04d6b01fc73fb takes care of renaming. 
The cargo subcommand is out of the scope of what I am doing for now. I'l focus on treating edge cases and tests for the current plugin. Also I wanted to do some gpu processing with rust as a demo in https://github.com/sdwolf/rustfromerl and that requires understanding a lot of voodoo magic.

I will make a PR to add both repos to the examples.
